interface StoredOtp {
  phone: string;
  code: string;
  carrierStatus: string;
  carrierReason?: string;
  expiresAt: number;
}

// In-memory cache for recent OTP codes generated by OTP.dev
const otpStore = new Map<string, StoredOtp>();

export function storePendingOtp(
  phone: string,
  code: string,
  carrierStatus = 'sent',
  carrierReason = '',
  ttlMs = 15 * 60 * 1000
) {
  const cleanPhone = phone.replace(/\D/g, '');
  otpStore.set(cleanPhone, {
    phone: cleanPhone,
    code: code.trim(),
    carrierStatus,
    carrierReason,
    expiresAt: Date.now() + ttlMs,
  });
}

export function getPendingOtp(phone: string): StoredOtp | null {
  const cleanPhone = phone.replace(/\D/g, '');
  const entry = otpStore.get(cleanPhone);
  if (!entry) return null;
  if (Date.now() > entry.expiresAt) {
    otpStore.delete(cleanPhone);
    return null;
  }
  return entry;
}

export function verifyPendingOtp(phone: string, inputCode: string): boolean {
  const cleanPhone = phone.replace(/\D/g, '');
  const entry = getPendingOtp(cleanPhone);
  if (!entry) return false;
  return entry.code === inputCode.trim();
}
